template = "https://github.com/giellalt/template-lang-und"
rev_id = 269
template_sha = "c43b39fe5507de4cc3a96e60743ab44578e61fd2"

[replacements]
__GLOTTOLOG_ID__ = "veps1250"
__REPO__ = "lang-vep"
__UND2C__ = "vep"
__UNDEFINED__ = "Veps"
__UND__ = "vep"
